#!/bin/bash

source "$(dirname "$0")/../logging.sh"

log "Installing Flatpak applications..."

local -a mokey_flathub_install=(
    "com.github.wwmm.easyeffects"
    "com.obsproject.Studio"
    "com.obsproject.Studio.Plugin.OBSVkCapture"
    "org.freedesktop.Platform.VulkanLayer.OBSVkCapture"
    "oject.Studio.Plugin.GStreamerVaapi"
    "com.obsproject.Studio.Plugin.Gstreamer"
    "com.visualstudio.code"
    "com.valvesoftware.Steam"
    "network.loki.Session"
    "org.blender.Blender"
    "org.freedesktop.Platform.VulkanLayer.MangoHud"
    "org.mozilla.Thunderbird"
    "org.pipewire.Helvum"
    "org.signal.Signal"
    "md.obsidian.Obsidian"
    "com.jgraph.drawio.desktop"
    "org.gimp.GIMP"
    "org.videolan.VLC"
    "io.github.shiftey.Desktop"
    "com.teamspeak.TeamSpeak"
    "dev.vencord.Vesktop"
    "com.spotify.Client"
    "com.heroicgameslauncher.hgl"
    "com.jetbrains.IntelliJ-IDEA-Community"
    "com.jetbrains.PyCharm-Community"
    "com.axosoft.GitKraken"
    "com.getpostman.Postman"
    "io.dbeaver.DBeaverCommunity"
    "org.wireshark.Wireshark"
    "com.github.mtkennerly.ludusavi"
    "com.valvesoftware.SteamLink"
    "org.tenacityaudio.Tenacity"
)
flatpak install -y flathub "${mokey_flathub_install[@]}"